### ISSUE TITLE
Uninstalling or updating to newer version giving error.

### ISSUE THREAD

**Issue by IzukuDeku01** [jerry048/Shared-Seedbox#1]
I installed this qbitTorrent a few months ago in my seedbox. But now there's some new and optimized v of qbit has released so I was gonna update it to the latest one but when I ran the script again for the update it gave an error 

[
Bad command line:
You cannot use -d (or --daemon): qBittorrent is already running for this user.
Run application with -h option to read about command line parameters.
/dev/fd/53: line 174: Decision2: command not found
rm: cannot remove '/home/Gofex/.seedbox_installation.sh': No such file or directory
]

++ now even the old qbit isn't working for some reason and if I delete the nox file from bin folder it comes back. so is there any way I can do a clean uninstall so that I can install the new version in my seedbox?

Seedbox is byte-sized btw.

**Comment by jerry048** [comment]
What is the version you are originally running?
And what method do you use in installation

**Comment by IzukuDeku01** [comment]
> What is the version you are originally running? And what method do you use in installation

last time I used was V 4.1.9.1 but I wanted to use the V 4.3.5 so I run "bash <(wget -qO- https://raw.githubusercontent.com/jerry048/Shared-Seedbox/main/qBittorrent.sh) UN PS WP ICPort Cache Size" again and when I selected 3) Daemon for the method it showed the mentioned error and now even the old one isn't working :(

I only Used the 3) Daemon method till now every time I installed qbit via ssh in any box

**Comment by jerry048** [comment]
Sorry for the late response
Essentially you want to 
1. Stop the restart by removing `*/1 * * * * $HOME/.qBittorrent-restart.sh` in crontab.
2. Kill the qBittorrent process by `pkill qbittorrent-nox`
3. Remove the password field in the config file by deleting the `WebUI\Password_ha1=xxxxxxxx` line in `/home/$qBittorrent_user_name/.config/qBittorrent/qBittorrent.conf`

Then I think you can just run the script again.
