### ISSUE TITLE
Support for qbittorrent 4.5

### ISSUE THREAD

**Issue by Ramton03** [jerry048/Shared-Seedbox#2]
Will there be any support for qbit 4.5?

**Comment by jerry048** [comment]
Sorry for the late reply. I will update to support qBittorrent 4.4 and 4.5 later. Probably with libtorrent 1.2 (and maybe 2.0)

**Comment by jerry048** [comment]
Updated

**Comment by Ramton03** [comment]
> Updated

Thanks :)
